### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by miyamot0** [Lakret/cells#1]
Loving this so far -- do you have a license in mind?

**Comment by Lakret** [comment]
I didn't consider it to be useful for other people apart from an example in a specific video and I don't have any plans to maintain it, but if you'd like I can add a license, and ofc. will be happy to see if you or others do something with it! 

I can imagine licensing it either as [CC BY](https://creativecommons.org/licenses/by/4.0/) or as MIT, will be glad to hear your thoughts.

**Comment by miyamot0** [comment]
MIT would be great!

**Comment by Lakret** [comment]
Done!
